[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "advent"
version = "0.1.0"
description = "Simple functional Python library designed for learning and problem solving purposes inspired by APL and Elixir programming languages."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
